### ISSUE TITLE
Fonts not rendering

### ISSUE THREAD

**Issue by Groctel** [adi1090x/rofi#14]
Hi!

First of all, thank you for your amazing work with this and other tools!

I've been trying to use the mpd, time and other applets but I haven't been able to make the, work due to fonts not rendering. For example, this is how `time.sh` opens for me:

![time applet](https://i.imgur.com/33Gm84P.png)

Both Comfortaa and Hurmit Nerd Font are installed (I'm using the AUR packages but the problem still exists when installing then to `~/.local/share/fonts`) and I'm running `rofi-git`, which is already at 1.5.4. Here you can see I can run the dock with no problems at all:

![dock](https://i.imgur.com/xIa6bkx.png)

I'm at a complete loss here. Is there anything I'm missing? I've checked that the dependencies are all installed and I don't see where the problem is :(

**Comment by adi1090x** [comment]
See, that's the problem here... Applets only works with rofi 1.5.4, not with AUR version (which is the latest bleeding edge version). If you want to use Applets, install rofi from official arch repo. But then the app dock won't work as expected. You can either use Applets or launchers. I can't fix this issue till next stable release of rofi.

**Comment by Groctel** [comment]
Oh! I confused rofi 1.5.4 with rofi 1.5.4 plus the git description. Thanks for the help and sorry for the inconvenience.

**Comment by JonnyHaystack** [comment]
I'm having this problem with the official rofi 1.5.4 package from Arch repos
