### ISSUE TITLE
Invoking options multiple times

### ISSUE THREAD

**Issue by dustinlacewell** [adi1090x/rofi#6]
If you want to increase the brightness, volume, etc more than just once, is there a good way of doing this?

**Comment by adi1090x** [comment]
rofi doesn't support multiple instances yet.

**Comment by dustinlacewell** [comment]
I'm not sure what you mean by multiple instances? Wouldn't just reinvoking the brightness script after adjusting the brightness solve this issue? When I asked Dave he modified the brightness script to do that as an example of what to do. He also added an option to "quit" the applet which simply doesn't reinvoke it.

Don't you find that the applets go away make the ones like volume and brightness less useful?

**Comment by hugohabicht01** [comment]
I don't think it is appropriate to have this issue closed. He pointed out something that bugs me as well, since it is quite annoying that stuff gets only increased by a small amount and you then have to launch the script again. e.g. I have my volume on 5% and want to get it to 100%. This will take quite some time and having to launch the script over and over again isn't fun... You don't need multiple instances to solve this issue, you just need some kind of loop that relaunches the rofi UI until some certain key is pressed.
