### ISSUE TITLE
how do i change the style and launcher used in rofi?

### ISSUE THREAD

**Issue by Jackal-boop** [adi1090x/rofi#82]
im new to linux in general and rofi was pre installed with an i3 config im using. i installed your themes and such but after fiddling around in the config and searching forums and man pages i cant figure out how to change the launcher and theme.

**Comment by NoaVelasco** [comment]
I have been struggling with this for a while too . Sometimes I think the world forgets that newcomers to Linux (hi! 🙋‍♂️) don't know a lot of things.
Maybe I'm wrong, but I managed the quest by touching some .ravi files and with a keybinding in i3:
`bindsym $SHORTCUT exec /home/USERNAME/.config/rofi/launchers/colorful/launcher.sh`
I hope it helps.

**Comment by adi1090x** [comment]
Instructions on readme file.

**Comment by jpmorris** [comment]
Yes it's not totally clear. For the newbies rofi is not  a daemon that is configured and changes picked up immediately (like polybar --reload), it doesn't need a manual config refresh (like i3wm), rofi just runs and exits once you make a selection. So this runs each time. The docs should have a top-level summary because, by my count, at least 3 people didn't know this: 1) edit launcher 2) edit colors 3) **actually RUN the launcher.sh in the launcher folder to test** 4) integrate with your UI of choice

**Comment by DeepReef11** [comment]
I'd say I'm intermediate to linux (but totally new to rofi) and I did not understand at all that launcher.sh is what was supposed to be called to try it. 

Also, there's a typo in a rasi file (run,drun instead of run-drun).
